<a href="https://colab.research.google.com/github/theschool8/sudoku_solver/blob/main/sudoku_solver.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
sudoku = [[8, 0, 1, 9, 2, 0, 0, 0, 0], 
          [0, 4, 0, 8, 5, 0, 7, 2, 6], 
          [0, 5, 6, 0, 7, 3, 0, 9, 0], 
          [5, 9, 8, 0, 0, 4, 1, 0, 0],
          [7, 0, 0, 0, 0, 0, 5, 3, 0],
          [0, 0, 2, 6, 0, 0, 4, 0, 0],
          [9, 0, 0, 3, 0, 0, 6, 8, 0],
          [6, 8, 3, 1, 9, 0, 0, 5, 0],
          [0, 0, 0, 0, 0, 0, 0, 1, 3]]

In [10]:
import numpy as np
print(np.matrix(sudoku))

[[8 0 1 9 2 0 0 0 0]
 [0 4 0 8 5 0 7 2 6]
 [0 5 6 0 7 3 0 9 0]
 [5 9 8 0 0 4 1 0 0]
 [7 0 0 0 0 0 5 3 0]
 [0 0 2 6 0 0 4 0 0]
 [9 0 0 3 0 0 6 8 0]
 [6 8 3 1 9 0 0 5 0]
 [0 0 0 0 0 0 0 1 3]]


In [16]:
def possible(grid, row,column,n):
  for i in range(9):
    if grid[row][i] == n:
      return False
  for j in range(9):
    if grid[j][column] == n:
      return False
  x0 = (row // 3) * 3
  y0 = (column // 3) * 3
  for i in range(3):
    for j in range(3):
      if grid[i+x0][j+y0] == n:
        return False
  return True

In [17]:
def solve(grid):
  for i in range(9):
    for j in range(9):
      if grid[i][j] == 0:
        for n in range(1,10):
          if possible(grid, i, j, n):
            grid[i][j] = n
            solve(grid)
            grid[i][j] = 0
        return
  print(np.matrix(grid))

In [18]:
solve(sudoku)

[[8 7 1 9 2 6 3 4 5]
 [3 4 9 8 5 1 7 2 6]
 [2 5 6 4 7 3 8 9 1]
 [5 9 8 7 3 4 1 6 2]
 [7 6 4 2 1 9 5 3 8]
 [1 3 2 6 8 5 4 7 9]
 [9 1 5 3 4 2 6 8 7]
 [6 8 3 1 9 7 2 5 4]
 [4 2 7 5 6 8 9 1 3]]
